package me.fuji97.RegisterUI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import io.github.cdimascio.dotenv.Dotenv;
import me.fuji97.LoginUI.LoginForm;
import me.fuji97.chatUI.ChatForm;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.Locale;

public class RegisterUI {
    private JPanel Body;
    private JTextField inputUsername;
    private JPasswordField inputPassword;
    private JTextField inputDisplay;
    private JButton backButton;
    private JButton registerButton;

    public RegisterUI() {

        // Query Register
        // INSERT INTO user_data (Username, Password, DisplayName) VALUES (?, ?, ?);

        Dotenv dotenv = Dotenv.load();

        String url = dotenv.get("DB_URL");
        String db_username = dotenv.get("DB_USER");
        String db_password = dotenv.get("DB_PASSWORD");

        registerButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                String inputUser = inputUsername.getText();
                String inputPass = inputPassword.getText();
                String display = inputDisplay.getText();

                String sql = "INSERT INTO user_data (Username, Password, DisplayName) VALUES (?, ?, ?)";

                try {
                    assert url != null;
                    Connection conn = DriverManager.getConnection(url, db_username, db_password);
                    System.out.println("Connected successfully!");

                    PreparedStatement stm = conn.prepareStatement(sql);
                    stm.setString(1, inputUser);
                    stm.setString(2, inputPass);
                    stm.setString(3, display);

                    int rowsAffected = stm.executeUpdate();

                    if (rowsAffected > 0) {
                        System.out.printf("Register Success!\nWelcome %s\n", inputUser);
                        UIManager.put("OptionPane.messageFont", new Font("Tahoma", Font.PLAIN, 14));
                        UIManager.put("OptionPane.buttonFont", new Font("Tahoma", Font.PLAIN, 14));
                        JOptionPane.showMessageDialog(null, "Register Success!", "Register", JOptionPane.INFORMATION_MESSAGE);

                        // ปิดหน้าจอ login และเปิด ChatForm
                        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(Body);
                        currentFrame.dispose();
                        new ChatForm(display); // ส่ง DisplayName ไป
                    } else {
                        System.out.println("Register Failed!");
                        UIManager.put("OptionPane.messageFont", new Font("Tahoma", Font.PLAIN, 14));
                        UIManager.put("OptionPane.buttonFont", new Font("Tahoma", Font.PLAIN, 14));
                        JOptionPane.showMessageDialog(null, "Register Failed!", "Register", JOptionPane.ERROR_MESSAGE);
                    }

                    conn.close();

                } catch (SQLException ex) {
                    System.out.println("Connection Failed: " + ex.getMessage());
                    UIManager.put("OptionPane.messageFont", new Font("Tahoma", Font.PLAIN, 14));
                    UIManager.put("OptionPane.buttonFont", new Font("Tahoma", Font.PLAIN, 14));
                    JOptionPane.showMessageDialog(null, "Failed to connect DB", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        //Back กลับไปที่ Login
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(Body);
                currentFrame.dispose();
                new LoginForm();
            }
        });
    }

    public JPanel getBody() {
        return Body;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Body = new JPanel();
        Body.setLayout(new GridLayoutManager(11, 5, new Insets(0, 0, 0, 0), -1, -1));
        Body.setMaximumSize(new Dimension(400, 350));
        Body.setMinimumSize(new Dimension(400, 350));
        Body.setPreferredSize(new Dimension(400, 350));
        final JLabel label1 = new JLabel();
        label1.setEnabled(true);
        Font label1Font = this.$$$getFont$$$("Sarabun", Font.BOLD, 15, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Register");
        Body.add(label1, new GridConstraints(1, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        Body.add(spacer1, new GridConstraints(10, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        inputUsername = new JTextField();
        Font inputUsernameFont = this.$$$getFont$$$("Arial", Font.PLAIN, 14, inputUsername.getFont());
        if (inputUsernameFont != null) inputUsername.setFont(inputUsernameFont);
        Body.add(inputUsername, new GridConstraints(3, 2, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer2 = new Spacer();
        Body.add(spacer2, new GridConstraints(3, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, 1, null, new Dimension(70, -1), null, 0, false));
        final Spacer spacer3 = new Spacer();
        Body.add(spacer3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, 1, null, new Dimension(70, -1), null, 0, false));
        final Spacer spacer4 = new Spacer();
        Body.add(spacer4, new GridConstraints(2, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 35), null, 0, false));
        final Spacer spacer5 = new Spacer();
        Body.add(spacer5, new GridConstraints(0, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Username: ");
        Body.add(label2, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        inputPassword = new JPasswordField();
        Body.add(inputPassword, new GridConstraints(5, 2, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer6 = new Spacer();
        Body.add(spacer6, new GridConstraints(4, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 30), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Password: ");
        Body.add(label3, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        inputDisplay = new JTextField();
        Font inputDisplayFont = this.$$$getFont$$$("Arial", Font.PLAIN, 14, inputDisplay.getFont());
        if (inputDisplayFont != null) inputDisplay.setFont(inputDisplayFont);
        Body.add(inputDisplay, new GridConstraints(7, 2, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer7 = new Spacer();
        Body.add(spacer7, new GridConstraints(6, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 30), null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Display Name: ");
        Body.add(label4, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 5, new Insets(0, 0, 0, 0), -1, -1));
        Body.add(panel1, new GridConstraints(9, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        backButton = new JButton();
        backButton.setText("<< Back");
        panel1.add(backButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(20, 30), null, 0, false));
        registerButton = new JButton();
        registerButton.setText("Register");
        panel1.add(registerButton, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(60, 30), null, 0, false));
        final Spacer spacer8 = new Spacer();
        panel1.add(spacer8, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, 1, null, new Dimension(20, -1), null, 0, false));
        final Spacer spacer9 = new Spacer();
        panel1.add(spacer9, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, 1, null, new Dimension(20, -1), null, 0, false));
        final Spacer spacer10 = new Spacer();
        panel1.add(spacer10, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, 1, null, new Dimension(20, -1), null, 0, false));
        final Spacer spacer11 = new Spacer();
        Body.add(spacer11, new GridConstraints(8, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Body;
    }

}
